spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yoedu_demo?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    properties:
      hibernate:
        format_sql: true