spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yoedu_demo?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    issuer: ${APP_JWT_ISSUER}
    secret: ${APP_JWT_SECRET}
    access-token-ttl-minutes: ${APP_JWT_ACCESS_TTL_MINUTES:15}
    refresh-token-ttl-days: ${APP_JWT_REFRESH_TTL_DAYS:30}
