spring:
  application:
    name: yoedu_backend
  profiles:
    active: ${APP_PROFILE:dev}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: kakaka7424@gmail.com
    password: 127011
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  sql:
    init:
      mode: never
server:
  port: 8080

