spring:
  application:
    name: yoedu_backend
  profiles:
    active: ${APP_PROFILE:dev}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
server:
  port:8080